usharesoft/appcenter-docs

admin/en/source/pages/config/populate-db-OS.rst
admin/en/source/pages/upgrade/upgrade-overview.rst

- Admin Guide: Added warning, that for migration major versions of RHEL and CentOS should be populated
- Fixed shell script parser warning

UFORGE-4115 documentation: migration needs major versions

---

admin/en/make.bat
admin/en/source/conf.py
end-user/en/make.bat
end-user/en/source/conf.py

Note, no need to add new rules for Makefile (linux builds) as latexpdf already available as target

Added pdf generation for windows machines 

---

admin/en/source/pages/config/populate-db-OS.rst

+ If executed with a copy-paste of provided command line, step 7 is uneffective but does not display any error message. I think ``repoIds`` information should be added to help user typing right command.
+ fix a little typo in step 6

Add information about `repoIds` option to step 7 in Populating Database OS

---

admin/en/source/pages/config/populate-db-OS.rst

Some parts of the example are given for x86_64 architecture, others for i386. It may be better to give a consistent example for only one architecture.

Uniformize architecture of the example in Populating Database OS

---

admin/en/source/pages/config/populate-db-OS.rst
end-user/en/source/pages/apis/python-cli.rst
end-user/en/source/pages/collaboration/wks-share-appliance.rst

New step added to make it clear that you must execute uforgecli while connected to a UForge instance when adding an OS.

Fixed warnings and display shifts and added steps for OS install

---

end-user/en/source/pages/getting-started.rst

- Added the browser list (for some reason this was no longer in 3.5.1 either)

UFORGE-4597 "Supported Browsers for the UI" is missing

---

admin/en/source/pages/tools/cli-overview.rst

- no longer using code block for this, rather just text (as it contains ' characters, which is interpreted)

UFORGE-4979 Cli documentation has meaningless red or blue color

---

admin/en/source/pages/manage-resources/windows.rst

- Removed step that is now done automatically by UForge during generation of windows images. We no longer require to add manually uforge-install-config when creating Windows golden images

UFORGE-3935 Admin guide - Windows golden creation

---

admin/en/source/pages/config/add-compute-node.rst

- Added extra information that the /space directory can be mounted

UFORGE-3424 explain that the /space disk space on generation nodes

---

admin/en/source/pages/rebranding/custo-footer.rst
end-user/en/source/pages/templating/appliance-advanced-partition.rst
end-user/en/source/pages/templating/appliance-generate.rst
end-user/en/source/pages/templating/appliance-installprofile.rst

Updated the docs i the install profile and generation sections to warn users on the disk size they are choosing, specifically Windows based os appliance templates.  Providing minimal disk size guidelines for "core" and "full" windows versions.

UFORGE-4839 Windows Core Edition golden images minimal size must be 12GB instead of 9GB

---

end-user/en/source/pages/getting-started.rst

1.
I removed  the description about UForgeNow.
Instead, place a description for signin in to UForge Potal.
2.
Remove the description about Marketplace.

Remove link to UForgeNow

---

end-user/en/source/pages/migration/migration-details.rst
end-user/en/source/pages/migration/whitebox-migration.rst

- add a warning related to hardlink while wite box migration in case partitining has been changed.

UFORGE-4587 migration breaks hardlink.

---

admin/en/source/pages/manage-resources/golden-create.rst
admin/en/source/pages/manage-resources/golden-storing.rst
end-user/en/source/pages/migration/blackbox-migration.rst

For publishing on K5 Windows images, there are some specific steps to do. 
Cf. https://projects.usharesoft.com/issues/6065 and https://projects.usharesoft.com/issues/5954
_Note: I've just noticed that my text editor removed unnecessary spaces. I don't think it's a problem but if you feel so, tell me, I will restore them to avoid confusion._

Add K5/Windows specific instructions for golden creation and blackbox migration

---

admin/en/source/pages/config/populate-db-OS.rst

This modification is for issues 7393 and 7395 to improve clarity of the warning about tag --officiallySupported

modify warning about --officiallySupported - in 3.7

---

admin/en/source/pages/changelog.rst
apis/en/source/pages/changelog.rst
end-user/en/source/pages/changelog.rst

The original release date was July 24, but USS decided to change the date
to July 25 because of a delay in fixing an issue.

update release notes to change the release date because of the delay

---

end-user/en/source/pages/migration/blackbox-migration.rst
end-user/en/source/pages/templating/supported-os.rst

Publications to Microsoft Azure platform require to install WALinuxAgent 2.0.18 (for CentOS) or waagent 2.0.16 (for Debian and Ubuntu) which are not compatible with NetworkManager package.

Complete blackbox migration doc for Azure image.

---

end-user/en/source/pages/templating/supported-os.rst

As UForge does not yet support K5 target format for RedHat Enterprise Linux
based images, it must be precised in documentation

Add RHEL limitation for K5 target format into documentation

---

admin/en/source/index.rst
apis/en/source/index.rst
end-user/en/source/index.rst
end-user/en/source/pages/apis/using-apis.rst

Issues regarding the APIs page in the end user doc where none of the links to the API docs were working.  Have fixed this using the correct intersphinx mapping syntax.

Fixed all the broken links to the API docs section

---

end-user/en/source/pages/migration/source-target-diffs.rst

- This explains why the file size is different between the source machine and the target machine

Added information regarding GRUB2 core.img size

---

venv.sh

- Add double quotes arround the path to avoid error due to the space inside "uForge API"

Fix to handle "uForge API" directory name

---

changelog.rst

- Azure agent version 2.2.14-1 for Debian 8
- Azure agent version 2.2.18-3 for Debian 9

Indicate new Azure agent version for Debian in release note

---

venv.sh

Test was not working in case of several scripts embedded, like when we use it from a jenkinsfile e.g. 
(return 0 2>/dev/null) executes return in a subshell and suppresses the error message; afterwards the exit code indicates whether the script was sourced (0) or not (1), which is used with the && and || operators to set the sourced variable accordingly.
Cf. https://stackoverflow.com/a/28776166/4469222

Fix test to detect if script is being sourced or not

---

requirements.txt

No longer pinning sphinx to 1.7.8 which doesn't work anymore

Fixed sphinx version to use latest sphinx
