- README.md
- uforge-appcenter/end-user/en/source/pages/getting-started.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-clone.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-config.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-create.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-generate.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-installprofile.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-os-updates.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-osprofile.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-software.rst
- uforge-appcenter/end-user/en/source/pages/templating/appliance-update.rst
- Added references to all the sections
- Updated the readme
> Fixed links to the docs

- admin/en/source/pages/install/configure-uforge.rst
- end-user/en/source/pages/getting-started.rst
- Adding information on browswer support and required flash plugin for the instllation wizard)
For supported browsers - in the End User Guide (as part of Getting Started section)
For installation wizard - in Admin Guide Iinstallation -> Configuring UForge)
> UFORGE-4110

- admin/en/source/pages/install/cloud-platform-ports.rst
- admin/en/source/pages/install/configure-uforge.rst
- admin/en/source/pages/install/overview.rst
- Added a summary of port numbers used by the main cloud platforms
- Added this ref to the installation section
> UFORGE-4234 publish connectors incoming and outgoing ports

- admin/en/source/pages/install/configure-uforge.rst
- Added NTP notes to the admin guide
> UFORGE-4185 documentation for NTP settings

- admin/en/source/pages/monitoring/overview.rst
- admin/en/source/pages/monitoring/support.rst
Correctly documenting the support script used to recuperate information of an UForge node
> UFORGE-4026

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/manage-resources/windows.rst
- admin/en/source/pages/manage-users/rbac/subscription-profiles.rst
- admin/en/source/pages/upgrade/upgrade-overview.rst
-UFORGE-4524
-UFORGE-4467
-UFORGE-4488
-UFORGE-4608
> ongoing bug fixes

- admin/en/source/pages/install/configure-uforge.rst
Wrongly deleted note about Flex.
> re-adding note about Flex

- end-user/en/source/pages/getting-started.rst
- Added the list of supported browsers for 3.6
> UFORGE-4597 "Supported Browsers for the UI" is missing

- admin/en/source/pages/install/configure-uforge.rst
- added warning message in the configuration section
> UFORGE-4675 IL2 admin passwords set in log files

- admin/en/source/pages/install/configure-uforge.rst
- admin/en/source/pages/manage-users/set-format-access.rst
- added warning in the configuration section
> UFORGE-4676 IL2 admin passwords set in log files

- admin/en/source/conf.py
> Changed copyright

- end-user/en/source/conf.py
> Fixed build failure for rtd

- admin/en/source/pages/install/install-ISO.rst
- end-user/en/source/pages/apis/using-python-sdk.rst
bug fix to add API root context
> 3.5.1 bug fix

- admin/en/source/pages/config/proprietary-pkg.rst
- still required, though cleaned up this page to make it easier to read
> UFORGE-4974 launch_distro_sorter.sh should be removed from the docs

- end-user/en/source/pages/getting-started.rst
- Added a warning that the user should check target cloud env supported OSes and added microsoft azure link as an example
> UFORGE-4721 Microsoft Azure - Supported OS list

- admin/en/source/pages/config/populate-db-OS.rst
- Fixed the indenting for the bullets
- Ensured that the URLs are now correct for repos
> UFORGE-4605 Mistake in url http://distros-repository.usharesoft.com

- admin/en/source/pages/config/populate-db-OS.rst
- All the URLs are set correctly
- Fixed some padding issues for the list (bullet 6)
> UFORGE-4605 Mistake in url http://distros-repository.usharesoft.com 

- admin/en/source/pages/backup/backup-idm.rst
- admin/en/source/pages/config/add-compute-node.rst
- admin/en/source/pages/config/config-database.rst
- admin/en/source/pages/config/config-smtp.rst
- admin/en/source/pages/config/config-webservice.rst
- admin/en/source/pages/config/email-notification.rst
- admin/en/source/pages/config/event-bus.rst
- admin/en/source/pages/config/modify-ip.rst
- admin/en/source/pages/config/populate-db-OS.rst
- Reviewed all the docs that uses uforge.conf and auth.conf and made appropriate changes
> UFORGE-5065 documentation for IDM backup restore misses one step

- admin/en/source/pages/install/test-deployment.rst
- Fixed the procedure to test the database is up and running
> UFORGE-5102 "Testing the Deployment" in AdminDoc3.6

- admin/en/source/pages/config/tuning-services.rst
- Fixed wrong file name in the documentation.  Should be: services_conf.json
> UFORGE-5099 Wrong procedure in tuning services

- admin/en/source/pages/config/config-scheduler.rst
- end-user/en/source/pages/templating/appliance-osprofile.rst
- Have added the procedure to remove a resource from a compute node
> UFORGE-5104 Could you write how to remove a Resource of OAR.

- admin/en/source/pages/config/populate-db-OS.rst
- Fixed the URLs for each OS repository hosted by UShareSoft
> UFORGE-5132 OS Repo URLs are wrong

- admin/en/source/pages/architecture/platform-overview.rst
- Correct, this was a mistake.  Updated docs with minimum requirements
> UFORGE-5157 Minimum Storage might be not 2GB

- admin/en/source/pages/rebranding/custo-footer.rst
> UFORGE-4896 showUForgeUrl (require to remove)

- Makefile
- README.md
- admin/en/source/conf.py
- end-user/en/source/conf.py
- end-user/en/source/pages/apis/using-apis.rst
- Added reference from the end user guide to the api guide
- Added a new Makefile to compile all the docs in the correct order
- Updated the README to compile all the docs at once
> - Added dependency between api doc <--> end user guide

- end-user/en/source/pages/templating/appliance-advanced-partition.rst
- Fixed spelling mistakes in this doc
> UFORGE-5306 Mispelling in "Physical Extend" > "Physical Extent" docs

- admin/en/source/pages/manage-resources/manage-milestone.rst
- admin/en/source/pages/manage-resources/manage-os.rst
Adding a note to indicate that when adding a major version, milestones are automatically created
> UFORGE-4184 add note about milestone when install major version

- admin/en/source/pages/install/install-ISO.rst
Modifying the install from ISO step to note that timezone and keyboard need to be set up twice
> uforge-5406 modify install ISO step 8

- admin/en/source/pages/config/proprietary-pkg.rst
Adding 2 new steps and fixing indent issues with code block
> uforge-5421 add missing steps and fix indent

- end-user/en/source/pages/templating/appliance-publish.rst
Fix typo in "information" step 1 found by Alex
> fix typo information

- admin/en/source/pages/manage-resources/manage-formats.rst
- admin/en/source/pages/manage-users/rbac/create-roles.rst
- admin/en/source/pages/manage-users/rbac/subscription-profiles.rst
- admin/en/source/pages/manage-users/set-format-access.rst
- admin/en/source/pages/manage-users/set-os-permissions.rst
Reviewed information about subscription profile to add --allusers and to state possibility to modify formats, OS, roles via subscription profiles. Needs Alex review before pulling to 3.6 branch.
> uforge-5522 and 5523 : update info on subscription profiles

- end-user/en/source/pages/templating/appliance-publish.rst
cherry-pick changes from master
> uforge-5506 RFE to improve image publish

- end-user/en/source/pages/apis/using-python-sdk.rst
> adding python examples from Pablo - needs review

- admin/en/source/pages/manage-resources/windows.rst
This change adds steps for expire admin password
> add step for windows golden create re uforge-5610

- end-user/en/source/pages/templating/appliance-generate.rst
> updates to docker generation following review

- admin/en/source/pages/manage-resources/windows.rst
- end-user/en/source/pages/apis/using-python-sdk.rst
Adds steps to create golden image because of issue 5610 : expire admin password
> Uforge 6017 in 3.6

- end-user/en/source/pages/apis/python-install-linux.rst
- end-user/en/source/pages/getting-started.rst
- end-user/en/source/pages/templating/appliance-create.rst
- end-user/en/source/pages/templating/appliance-generate.rst
- end-user/en/source/pages/templating/supported-os.rst
Please also see my ToDO-Note that is not part of the complied docu. Based on the discussion this sentence can be fixed as well. 
This is a small pull request because I need to get more familiar with this and I created this one differently as before. Next one will be with more changes included.
> minor adjustments for templating, getting started and python-api

- admin/en/source/pages/rebranding/custo-platform.rst
> update command to customize email

- admin/en/source/pages/rebranding/custo-platform.rst
> update command to customize email in 3.6

- admin/en/source/pages/rebranding/restrict-usage.rst
- New flags added to do this properly.  Updated the documentation on how to do this in the configuration file of the UI.
> UFORGE-4902 Format enabling/disabling not working when updating the UI

- admin/en/source/pages/rebranding/custo-footer.rst
and hormonize the Title for Footer Modification with the other Titles
> make footer Terms of Use and Privacy Policy rules more clear

- admin/en/source/pages/manage-resources/golden-create.rst
I have updated "golden-create.rst", because the new feature, Windows Drivers Injection Improvement, has changed the steps to create a golden image. The new method has significantly simplified the procedure that a user should follow.
> Windows drivers injection

- admin/en/source/pages/manage-users/rbac/create-roles.rst
- end-user/en/source/pages/migration/scan-to-appliance.rst
This covers only part of the changes requested for issue 6441.
> remove references to Studio

- end-user/en/source/pages/getting-started.rst
- end-user/en/source/pages/migration/scan-to-appliance.rst
- end-user/en/source/pages/templating/appliance-create.rst
- end-user/en/source/pages/templating/appliance-generate.rst
- end-user/en/source/pages/templating/appliance-os-updates.rst
- end-user/en/source/pages/templating/appliance-search.rst
- end-user/en/source/pages/templating/appliance-software.rst
- end-user/en/source/pages/templating/appliance-view-details.rst
- Changed all references from "VM Builder" -> "Apps"
> UFORGE-5787 Rename VM Builder Tab

- admin/en/source/pages/manage-resources/golden-create.rst
- end-user/en/source/pages/migration/blackbox-migration.rst
Have to disable NLA for K5 before golden creation and Windows blackbox migration.
_Note: I didn't find any Microsoft official documentation about how to do this, so I've put another article. Do you think it can do it or do we have to write a specific doc for this?_
> Add other K5 specific instructions 

- admin/en/source/pages/manage-resources/golden-create.rst
- end-user/en/source/pages/migration/blackbox-migration.rst
> K5 3.7 fp1

- admin/en/source/pages/install/configure-uforge.rst
- end-user/en/source/pages/migration/scanning.rst
- end-user/en/source/pages/templating/appliance-advanced-partition.rst
Applying some notes about issues with same LVM name during scan.
> 3.6.fp1 lvm

- admin/en/source/pages/install/configure-uforge.rst
- end-user/en/source/pages/migration/scanning.rst
- end-user/en/source/pages/templating/appliance-advanced-partition.rst
adding notes regarding LVM unique name to avoid errors during merge
> 3.6.fp2 lvm

- admin/en/source/pages/config/populate-db-OS.rst
> add warning indicating officiallysupported flag must be used 

- admin/en/source/pages/config/populate-db-OS.rst
For bug 6865, rolled back into 3.7.fp1
> add warning indicating officiallysupported flag must be used

- admin/en/source/pages/config/populate-db-OS.rst
-reorganizing the Populate DB OS page
-list of distrib repos stripped from example and set aside in new section
-section created for RHEL example => this will need to be reviewed !
> adding new section for RHEL example

- end-user/en/source/pages/migration/migration-details.rst
> adding preconditions for migration

- admin/en/source/pages/config/populate-db-OS.rst
> minor format indent changes

- admin/en/source/pages/config/populate-db-OS.rst
Following on issue 6803. Also added example for Ubuntu
> updated populate OS section with new RHEL example

- admin/en/source/pages/config/populate-db-OS.rst
also added example for Ubuntu
answers issue 6803
> added new example for RHEL populate os

- admin/en/source/pages/config/populate-db-OS.rst
and Ubuntu example
following issue 6803
> added new example for RHEL populate os 3.6.fp1

- admin/en/source/pages/config/populate-db-OS.rst
also added example for Ubuntu
following issue 6803
> added new example for RHEL populate os in 3.6

- admin/en/source/pages/manage-resources/windows.rst
> removing --name option for org golden list

- end-user/en/source/pages/apis/python-cli.rst
> update CLI install section

- admin/en/source/pages/manage-resources/golden-create.rst
> modify link to K5 Iaas documentation - master

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/manage-resources/golden-create.rst
> update link to K5 IaaS documentation - 3.7.fp2

- admin/en/source/pages/manage-resources/golden-create.rst
> modify link to K5 Iaas documentation - 3.7.fp1

- admin/en/source/pages/manage-resources/golden-create.rst
> modify link to K5 Iaas documentation - 3.7

- admin/en/source/pages/rebranding/custo-footer.rst
- admin/en/source/pages/rebranding/custo-header.rst
information added for examples both in header and footer pages
> adding info about option to open target in new tab

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/config/proprietary-pkg.rst
> remove duplicate steps for RHEL repo and mention RedHat satellite - master

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/config/proprietary-pkg.rst
> remove duplicate steps for RHEL repo and mention RedHat satellite - 3.7.fp2

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/config/proprietary-pkg.rst
> remove duplicate steps for RHEL repo and mention RedHat satellite - 3.7.fp1

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/config/proprietary-pkg.rst
> remove duplicate steps for RHEL repo and mention RedHat satellite

- end-user/en/source/pages/templating/appliance-create.rst
some images not visible as not properly formatted
> making images visible

- admin/en/source/pages/changelog.rst
- apis/en/source/index.rst
- apis/en/source/pages/apikey/apiKey_create.rst
- apis/en/source/pages/apikey/apiKey_delete.rst
- apis/en/source/pages/apikey/apiKey_getAll.rst
- apis/en/source/pages/apikey/overview.rst
- apis/en/source/pages/applianceosprofile/applianceOSProfilePkg_getAll.rst
- apis/en/source/pages/applianceosprofile/applianceOSProfile_create.rst
- apis/en/source/pages/applianceosprofile/overview.rst
- apis/en/source/pages/changelog.rst
- apis/en/source/pages/dto-objects/APIKeyPair.rst
- apis/en/source/pages/dto-objects/PublishImageAws.rst
- apis/en/source/pages/dto-objects/Scan.rst
- apis/en/source/pages/dto-objects/WinMsiApplication.rst
- apis/en/source/pages/dto-objects/WinService.rst
- apis/en/source/pages/dto-objects/WindowsProfile.rst
- apis/en/source/pages/dto-objects/overview.rst
- end-user/en/source/pages/changelog.rst
- Updated API docs automatically built from the FP3 release candidate
- Added the release notes for FP3
> - Updated the API docs + Release notes

- apis/en/source/pages/dto-objects/StatDataPoint.rst
- apis/en/source/pages/dto-objects/StatDataPoints.rst
- apis/en/source/pages/dto-objects/UserStat.rst
- apis/en/source/pages/dto-objects/UserStats.rst
- apis/en/source/pages/dto-objects/overview.rst
- apis/en/source/pages/userquotaandusage/userStats_get.rst
- Updated the userStats_get with a better description
- New UserStat object
- Better description for the other stats objects
> UFORGE-7252 Dashboard Stats - API Doc Changes

- end-user/en/source/pages/myaccount/user-profile.rst
Clearer explanation on how quotas work and explanation on the information displayed.
> Updated the docs for the dashboard.  

- admin/en/source/pages/config/populate-db-OS.rst
- end-user/en/source/pages/migration/migration-details.rst
> add note to indicate need minor versions for scan efficiency - master

- admin/en/source/pages/config/populate-db-OS.rst
- end-user/en/source/pages/migration/migration-details.rst
> add note to indicate need minor versions for scan efficiency - fp3

- admin/en/source/pages/config/populate-db-OS.rst
> modify warning about --officiallySupported flag

- admin/en/source/pages/config/populate-db-OS.rst
> fix command line example for RedHat create OS profile - 3.7

- admin/en/source/pages/config/populate-db-OS.rst
> fix command line example for RedHat create OS profile - master

- end-user/en/source/pages/migration/scanning.rst
> remove sentence that indicates scan limit

- end-user/en/source/pages/migration/scanning.rst
> remove sentence that indicates scan limit - 3.7

- admin/en/source/pages/architecture/deployment-example.rst
- admin/en/source/pages/install/repository-setup.rst
Changes for issues 7701 and 7702
> add more info to min sw topology for core and nas - master

- admin/en/source/pages/config/config-scheduler.rst
This is to cover redmine issue 7399
> added info about modifying oar config to round-robin

- admin/en/source/pages/config/config-scheduler.rst
This is due to redmine issue 7399
> added info about modifying oar config to round-robin - in 3.7

- end-user/en/source/pages/templating/appliance-generate.rst
- end-user/en/source/pages/templating/appliance-publish.rst
- end-user/en/source/pages/templating/supported-os.rst
Adding link and info regarding vcenter connector for VMware for fp5
> add information regarding Vcenter connector

- end-user/en/source/pages/migration/blackbox-migration.rst
- end-user/en/source/pages/migration/scan-to-image.rst
- end-user/en/source/pages/templating/appliance-generate.rst
list services that are enabled/disabled after migration
> add info for state of services after migration

- admin/en/source/pages/changelog.rst
- apis/en/source/pages/changelog.rst
- end-user/en/source/pages/changelog.rst
Dear members,
Could you check if my modifications on release note for 3.7.fp5 are OK?
I have updated the release notes as follows:
- Add a new section of "3.7.fp5"
- Add a new feature, "scan to golden"
Sincerely yours,
--
Yuzuru Ueda
> update release note for 3.7.fp5

- admin/en/source/pages/changelog.rst
- apis/en/source/pages/changelog.rst
- end-user/en/source/pages/changelog.rst
as well as 1 new bug fix for 3.7-5 rc5
> adding 3.7-5 rc4 bugs to release notes

- end-user/en/source/pages/apis/using-apis.rst
- Updated the simple request, response: now tomcat (no longer glassfish)
> - Added examples to the API section

- admin/en/source/pages/architecture/deployment-example.rst
> adding info for poc mononode and multinode example

- admin/en/source/pages/install/install-ISO.rst
> added a note to indicate install on /dev/sda in 3.6

- admin/en/source/pages/install/install-ISO.rst
> added a note to indicate install on /dev/sda in master

- admin/en/source/pages/changelog.rst
- apis/en/source/pages/changelog.rst
- end-user/en/source/pages/changelog.rst
- end-user/en/source/pages/templating/supported-os.rst
Add Ubuntu 16.04 to supported OS list and update RN for fp2 since this has been in since then
> add support for Ubuntu 16.04

- admin/en/source/pages/changelog.rst
- apis/en/source/pages/changelog.rst
- end-user/en/source/pages/changelog.rst
UEDA has updated the following sections for fp6.
- Enhancements
- Bug Fixes
> update release note for 3.7.fp6

- admin/en/source/pages/install/install-ISO.rst
> added a note to indicate install on /dev/sda in 3.7

- end-user/en/source/pages/templating/appliance-publish.rst
> add note about publish error for AWS - in 3.7

- end-user/en/source/pages/templating/appliance-publish.rst
This is in response to issue 6620 found by PS
> add note about publish error for AWS

- admin/en/source/pages/install/repository-local-storage.rst
> remove unnecessary install step - in 3.7 branch

- admin/en/source/pages/install/repository-local-storage.rst
> remove step to copy OS for install

- admin/en/source/pages/upgrade/upgrade-overview.rst
> adding note to make snapshot before upgrade

- admin/en/source/pages/manage-users/api-access.rst
> correct command user role add option - in 3.7

- admin/en/source/pages/manage-users/api-access.rst
> correct command user role add option

- admin/en/source/pages/changelog.rst
- apis/en/source/pages/changelog.rst
- end-user/en/source/pages/changelog.rst
Add a line in New Feature to tell K5 US, Finland and Spain regions are now supported.
> update release note for fp7: Support K5 multi-regions

- admin/en/source/pages/manage-resources/create-custom-os.rst
- admin/en/source/pages/monitoring/scheduler-jobs.rst
- admin/en/source/pages/monitoring/supervisor-mode.rst
-Since multi-org is not supported (issue 5327). 
-also fixed some formatting
-and removed a reference to glasses for supervisor mode
> remove ref to selecting org drop-down

- admin/en/source/pages/manage-resources/scan-to-golden.rst
> modify windows 2012R to 2012R2 - master

- admin/en/source/pages/install/repository-shared-storage.rst
Fix for issue 6093 requested by PS
> correct code to test mount point - 3.7

- admin/en/source/pages/install/repository-shared-storage.rst
> correct code to test mount point - master

- end-user/en/source/pages/migration/scanning.rst
as per issue raised by PS : 6106
> add note explaining what is not part of overlay

- admin/en/source/pages/config/email-notification.rst
- admin/en/source/pages/config/further-config-overview.rst
- admin/en/source/pages/config/modify-endpoints.rst
- admin/en/source/pages/config/modify-ip.rst
for mono node deployment only
This answers issue 6059
> add procedure to modify uforge IP

- end-user/en/source/pages/templating/deploy-machine-image.rst
Add Azure Resource Manager support into deployment documentation.
> Deploy azure support

- admin/en/source/pages/changelog.rst
- apis/en/source/pages/changelog.rst
- end-user/en/source/pages/changelog.rst
on the changelog pages, as per PS issue 7345
> corrected the version of hammr to install

- end-user/en/source/pages/migration/blackbox-migration.rst
> specify the file types not included in scan overlay

- end-user/en/source/pages/migration/overview.rst
- end-user/en/source/pages/migration/source-target-diffs.rst
- end-user/en/source/pages/templating/appliance-generate.rst
- added new section to explain diffs between source -> target
- removed section from the appliance templates regarding state changes and added this to the new migration differences section
> Added new section to explain differences between source -> target 

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/upgrade/upgrade-overview.rst
- end-user/en/source/pages/templating/supported-os.rst
> adding Oracle Linux to supported OS and fix build error

- admin/en/source/pages/upgrade/upgrade-overview.rst
- end-user/en/source/pages/migration/scanning.rst
Also (in separated commits):
- cleaned a Warning
- cleaned code (we should use # instead of numbers when creating an ordered list)
> Add doc info about the Scanned Instance Name for Windows

- admin/en/source/pages/config/tuning-services.rst
> Sentence correction for the section "Tuning for Migration Projects"

- end-user/en/source/pages/templating/appliance-create.rst
Add a note to explain how Windows Driver can be installed by a Software bundle.
> Note for Windows Driver Injection

- changelog.rst
- end-user/en/source/pages/migration/data-synchronization.rst
UForge server URL parameter of uforge-sync binary now expect the UForge API URL
( Merge #8739f11 by reverting #3a2e43a)
> UForge server URL parameter of uforge-sync binary now expect the UForge API URL

- end-user/en/source/pages/migration/source-target-diffs.rst
> explain network device name change after migration - UForge-7859

- end-user/en/source/pages/migration/blackbox-migration.rst
> add extra info about timezone in migration - UFORGE 5327

- admin/en/source/pages/manage-resources/windows.rst
> remove note that Windows migration limited to blackbox 

- admin/en/source/pages/manage-users/set-quotas.rst
> fix typo for quota limit

- admin/en/source/pages/manage-resources/windows.rst
> remove note that Windows migration limited to blackbox - 3.8 branch

- admin/en/source/pages/manage-users/set-quotas.rst
> fix typo for quota limit - 3.8 branch

- admin/en/source/pages/config/add-compute-node.rst
> update adding compute node procedure - master

- admin/en/source/pages/config/proprietary-pkg.rst
> update step for copying contents using rsync - master

- admin/en/source/pages/config/proprietary-pkg.rst
> update step for copying contents using rsync

- admin/en/source/pages/config/add-compute-node.rst
For issue 7802 and fix merge issue
> update adding compute node procedure

- admin/en/source/pages/architecture/storage-sizing.rst
> update the warning about log location

- admin/en/source/pages/architecture/storage-sizing.rst
> update the warning about log location - 3.8

- admin/en/source/pages/manage-resources/windows.rst
> update info on Windows key mechanism

- admin/en/source/pages/config/further-config-overview.rst
- admin/en/source/pages/config/populate-iso.rst
- admin/en/source/pages/install/repository-local-storage.rst
cherry-picked changes from master
> moving info to populate ISO skeletons to seperate section - 3.8

- admin/en/source/pages/config/proprietary-pkg.rst
- admin/en/source/pages/manage-resources/manage-milestone.rst
- admin/en/source/pages/manage-resources/manage-os.rst
> replace occurences of RedHat by Red Hat

- admin/en/source/pages/config/proprietary-pkg.rst
- admin/en/source/pages/manage-resources/manage-milestone.rst
- admin/en/source/pages/manage-resources/manage-os.rst
> replace occurences of RedHat by Red Hat - 3.8

- admin/en/source/pages/config/configure-ssl-cert.rst
- admin/en/source/pages/install/overview.rst
- admin/en/source/pages/install/repository-setup.rst
- admin/en/source/pages/manage-resources/manage-project-catalog.rst
- admin/en/source/pages/manage-resources/overview.rst
- admin/en/source/pages/manage-services/overview.rst
- admin/en/source/pages/manage-users/overview.rst
> remove ref to default project and rename some titles

- admin/en/source/pages/config/configure-ssl-cert.rst
- admin/en/source/pages/install/overview.rst
- admin/en/source/pages/install/repository-setup.rst
- admin/en/source/pages/manage-resources/manage-project-catalog.rst
- admin/en/source/pages/manage-resources/overview.rst
- admin/en/source/pages/manage-services/overview.rst
- admin/en/source/pages/manage-users/overview.rst
> remove ref to default project and rename some titles - 3.8

- admin/en/source/pages/backup/backup-database.rst
> modify path opt/opendj to all lowercase

- admin/en/source/pages/rebranding/overview.rst
- admin/en/source/pages/rebranding/restrict-usage.rst
> specify the correct config files

- end-user/en/source/pages/templating/appliance-generate.rst
> rephrase for clarity - 3.8

- end-user/en/source/pages/templating/appliance-generate.rst
> rephrase for clarity

- end-user/en/source/pages/templating/supported-os.rst
> specify 32bit and 64bit for centos and rh 5.2+ - 3.8

- end-user/en/source/pages/templating/appliance-osprofile.rst
> remove step to click search button

- end-user/en/source/pages/templating/appliance-update.rst
> remove step to save when adding logo since save is automatic - 3.8

- end-user/en/source/pages/templating/appliance-software.rst
> remove mention of save button - 3.8

- admin/en/source/pages/install/configure-uforge.rst
> add note in case uforge deployment wizard hangs - 3.8

- admin/en/source/pages/install/configure-uforge.rst
> add note in case uforge deployment wizard hangs

- admin/en/source/pages/manage-resources/create-custom-os.rst
> simple click instead of double click

- admin/en/source/pages/install/configure-uforge.rst
> updated requirements for admin pw when deploying wizard

- admin/en/source/pages/manage-resources/windows.rst
> update info on Windows key mechanism - 3.8

- admin/en/source/pages/install/configure-uforge.rst
> add note in case ntp not configured during install - master

- admin/en/source/index.rst
- admin/en/source/pages/install/configure-uforge.rst
- apis/en/source/index.rst
- end-user/en/source/index.rst
- end-user/en/source/pages/apis/using-apis.rst
For issue  8563
Also includes James's fix of API links
>  add note in case ntp not configured during install - 3.8.fp1

- admin/en/source/index.rst
- apis/en/source/index.rst
- end-user/en/source/index.rst
- end-user/en/source/pages/apis/using-apis.rst
- end-user/en/source/pages/templating/appliance-publish.rst
> clarify AWS publish error, SSH must be allowed - 3.8

- admin/en/source/index.rst
- apis/en/source/index.rst
- end-user/en/source/index.rst
- end-user/en/source/pages/apis/using-apis.rst
- end-user/en/source/pages/templating/appliance-publish.rst
- end-user/en/source/pages/templating/supported-os.rst
> adding Outscale as possible target - 3.8

- end-user/en/source/pages/migration/source-target-diffs.rst
> add new section to indicate diff in etc/fstab file after migration - master

- admin/en/source/index.rst
- apis/en/source/index.rst
- end-user/en/source/index.rst
- end-user/en/source/pages/apis/using-apis.rst
- end-user/en/source/pages/migration/source-target-diffs.rst
- end-user/en/source/pages/templating/appliance-publish.rst
> add new section to indicate diff in etc/fstab file after migration - 3.8

- end-user/en/source/pages/templating/appliance-publish.rst
- end-user/en/source/pages/templating/supported-os.rst
> adding Outscale as possible target - master

- admin/en/source/pages/install/configure-uforge.rst
> updated requirements for admin pw when deploying wizard - 3.8

- end-user/en/source/pages/templating/appliance-publish.rst
> clarify AWS publish error, SSH must be allowed -master

- end-user/en/source/pages/getting-started.rst
> update deployment description with complete list

- end-user/en/source/pages/getting-started.rst
> update deployment description with complete list - master

- admin/en/source/pages/architecture/platform-overview.rst
> replace orientated by oriented for ROA - 3.8

- admin/en/source/pages/architecture/platform-overview.rst
> replace orientated by oriented for ROA - master

- admin/en/source/pages/install/install-ISO.rst
> add a cleanup phase post install - master

- admin/en/source/pages/install/install-ISO.rst
> add a cleanup phase post install - 3.8

- changelog.rst
Removed duplicate bug reports between 3.8 and 3.8.fp1
> Added 3.8 release notes

- end-user/en/source/pages/credentials/user-cloud-accounts.rst
> edit to clarify ref to Microsoft ARM - master

- end-user/en/source/pages/credentials/user-cloud-accounts.rst
> edit to clarify ref to Microsoft ARM - 3.8

- changelog.rst
Reverts usharesoft/appcenter-docs#642
> Revert "Merge and update release note for Deploy Windows"

- admin/en/source/pages/rebranding/custo-user-profile.rst
> correct area to modify to restrict pw change on ui - 3.8

- admin/en/source/pages/rebranding/custo-user-profile.rst
> correct area to modify to restrict pw change on ui - master

- admin/en/source/pages/config/modify-endpoints.rst
> add UI node to list when modifying URL endpoint - 3.8

- end-user/en/source/pages/templating/appliance-import-export.rst
has been cherry-picked from master
> add a note for no Activation Key in an eported template

- end-user/en/source/pages/myaccount/user-profile.rst
- for issue 9576
- also delete step about save that is not needed
> delete duplicate information about disk usage - 3.8

- end-user/en/source/pages/myaccount/user-profile.rst
- for issue 9576
- also removed step about "save" that isn't required
> delete duplicate information about disk usage

- admin/en/source/pages/config/modify-endpoints.rst
> add UI node to list when modifying URL endpoint - master

- admin/en/source/pages/install/configure-uforge.rst
> remove ref to flex - master

- admin/en/source/pages/install/configure-uforge.rst
- end-user/en/source/pages/templating/supported-image-type.rst
- end-user/en/source/pages/templating/supported-os.rst
- for issue 9561
- also fixed merge issue because supporte images is now its own page
> add support for 11 esxi for OVF etc - 3.8

- end-user/en/source/pages/templating/appliance-create.rst
> appliances should be applications

- end-user/en/source/pages/templating/appliance-create.rst
- end-user/en/source/pages/templating/appliance-generate.rst
for issue 9565
- also merged with note that Docker not supported for Windows
>  appliances should be applications

- admin/en/source/pages/manage-resources/windows.rst
> fix wording in windows note - 3.8

- admin/en/source/pages/manage-resources/windows.rst
> fix wording in windows note

- end-user/en/source/pages/migration/scan-details.rst
> adding more details about applications in windows scan - 3.8

- end-user/en/source/pages/migration/scan-details.rst
> adding more details about applications in windows scan - master

- end-user/en/source/pages/migration/scanning.rst
> correct step on partitions to exclude for windows scan

- end-user/en/source/pages/templating/appliance-create.rst
> use correct name of uforge-install-config file -master

- end-user/en/source/pages/migration/scanning.rst
- end-user/en/source/pages/templating/appliance-create.rst
> use correct name of uforge-install-config file -3.8

- end-user/en/source/pages/migration/scanning.rst
> clarify step and note about using local storage

- admin/en/source/pages/backup/backup-database.rst
- admin/en/source/pages/config/add-compute-node.rst
- admin/en/source/pages/install/test-deployment.rst
- admin/en/source/pages/manage-services/start-database.rst
- admin/en/source/pages/upgrade/upgrade-overview.rst
-for issue 9440
-also cleanup merge error + indent issue
> modify service msql commands

- admin/en/source/pages/upgrade/migrating-to38.rst
> update migrate to 3.8 following PS review - 3.8

- admin/en/source/pages/upgrade/migrating-to38.rst
> update migrate to 3.8 following PS review

- admin/en/source/pages/config/config-amp.rst
> update config cloudsoft AMP procedure

- end-user/en/source/pages/migration/blackbox-migration.rst
- end-user/en/source/pages/migration/scanning.rst
> removing pre-reqs that are no longer needed before windows scan

- admin/en/source/pages/config/populate-db-OS.rst
- admin/en/source/pages/config/proprietary-pkg.rst
- admin/en/source/pages/config/update-OS-repo.rst
- admin/en/source/pages/manage-resources/manage-milestone.rst
- admin/en/source/pages/manage-users/admin-rights.rst
- admin/en/source/pages/manage-users/manage-users.rst
- admin/en/source/pages/monitoring/scheduler-jobs.rst
- end-user/en/source/pages/templating/appliance-advanced-partition.rst
> modify em dash to hyphen in code samples

- admin/en/source/pages/config/modify-ip.rst
> correct modify IP procedure

- admin/en/source/pages/config/modify-ip.rst
> add note that procedure is for mono-node only

- end-user/en/source/pages/templating/appliance-publish.rst
If we can put something better than 'yes' command, it might be nicer for the user
> First version to make image runnable on Openshift

- admin/en/source/index.rst
- admin/en/source/pages/gdpr/delete-user.rst
- admin/en/source/pages/gdpr/export-user.rst
- admin/en/source/pages/gdpr/overview.rst
- admin/en/source/pages/gdpr/retrieve-user.rst
Add new section for GDPR which includes:
-get user data
-exporting data
-deleting data
> create new section for gdpr

- end-user/en/source/pages/templating/appliance-create.rst
> remove ref to green icon

- end-user/en/source/pages/templating/appliance-create.rst
> remove ref to green icon - 3.8

- admin/en/source/pages/rebranding/custo-platform.rst
> missing command to modify root context - 3.8

- admin/en/source/pages/config/tuning-services.rst
> add note to restart tomcat to apply changes - 3.8

- admin/en/source/pages/rebranding/custo-platform.rst
> missing command to modify root context

- admin/en/source/_static/css/extra.css
- admin/en/source/conf.py
- apis/en/source/_static/css/extra.css
- apis/en/source/conf.py
- end-user/en/source/_static/css/extra.css
- end-user/en/source/conf.py
- changed the header to be red to reflect Fujitsu colour scheme
> Customized the rtd theme:

- admin/en/source/pages/upgrade/upgrade.rst
> wrong version for vault update note - fp3

- admin/en/source/pages/rebranding/restrict-usage.rst
> restrict cloud account displayed

- end-user/en/source/pages/templating/appliance-generate.rst
- end-user/en/source/pages/templating/appliance-installprofile.rst
> add note that only 1 disk for K5 and openstack

- admin/en/source/pages/manage-resources/manage-os.rst
> remove reference to defunct --org

- admin/en/source/pages/rebranding/custo-signin.rst
- changelog.rst
Added configuration information to update the Sign-Up page Opt-In message (for GDPR)
> Sign Up Opt-In Message (GDPR)

- end-user/en/source/pages/credentials/user-cloud-accounts.rst
> remove mention of X.509 Certificate

- admin/en/source/pages/config/populate-db-OS.rst
> clarify --name for org repo create

- end-user/en/source/pages/migration/whitebox-migration.rst
> modify note on multi-nics

- end-user/en/source/pages/templating/appliance-generate.rst
- Add step to enter entrypoint.
- Also removed wrong info about setting disk size (not appropriate here)
- Also after re-re-reading, seemed to me the last steps were not in the right order (talk about download and pop up before saying where the image is listed).
> add info about Docker entrypoint

- admin/en/source/pages/upgrade/migrating-to38.rst
> add extra step for golden images during upgrade

- changelog.rst
I have checked that each bug has a commit in the right version in uforge product.
> Add bug fixes to the fp5 release note

- end-user/en/source/pages/templating/appliance-create.rst
> correct note about windows install profile - 3.8

- end-user/en/source/pages/templating/appliance-create.rst
> correct note about windows install profile

- admin/en/source/pages/config/tuning-services.rst
> add note about event controller restart

- admin/en/source/pages/upgrade/upgrade.rst
> root_token needed also on compute node

- admin/en/source/pages/config/email-notification.rst
> remove refs to marketplace email notifications

- end-user/en/source/pages/migration/blackbox-migration.rst
for issue 11347.
This also fixes the broken link mentioned in issue 11344
> add a note about admin pw when migration Windows to K5 - fp6

- end-user/en/source/pages/migration/blackbox-migration.rst
> simplify step to uninstall networkmanager - fp6

- end-user/en/source/pages/generating/appliance-generate.rst
> add note about install profile for Docker images - fp6

- end-user/en/source/pages/getting-started.rst
> fix typo or -> of

- end-user/en/source/pages/credentials/user-cloud-accounts.rst
- end-user/en/source/pages/generating/appliance-publish.rst
> add instructions to setup AWS account to publish Windows images

- end-user/en/source/pages/migration/data-synchronization.rst
> add a note about uforge-sync overwriting files

- admin/en/source/pages/upgrade/upgrade.rst
> modify code for upgrade from fp5

- changelog.rst
- end-user/en/source/pages/deploying/deploy-machine-image.rst
integrate the changes provided by team piston
> document Windows appliance deployment to Azure

- end-user/en/source/pages/migration/data-synchronization.rst
> add note about sync for BTRFS

- admin/en/source/pages/manage-resources/golden-create.rst
Changed the warning message to be better understood.
> UFORGE-8607 Misleading warning about manual golden images

- end-user/en/source/pages/getting-started.rst
> add Edge to supported browser list

- end-user/en/source/pages/migration/scan-windows.rst
> adding note about windows scan log files

- changelog.rst
- end-user/en/source/pages/generating/image-generate.rst
- end-user/en/source/pages/generating/supported-image-type.rst
Remove restrictions about CentOS and Debian in doc and release note
> Add support for all Linux formats to software component Docker generation

- licensing.rst
> Add Filebeat as third party library

- admin/en/source/pages/config/config-amp.rst
> Add documentation to explain how to add the uforge plugin inside AMP

- end-user/en/source/pages/templating/appliance-publish.rst
- Added a new section to describe where Windows publish to Azure can be found and specificities about this publish.
- Also fixed issues with indentation in the previous section (Publish to KVM)
> adding section publish windows to azure for 3.8-6

- changelog.rst
Blueprint changelog for newcomposerview.
> Bp release note

- admin/en/source/pages/config/config-amp.rst
> Groovy script option is not required anymore on AMP server

- end-user/en/source/pages/generating/appliance-publish.rst
> add note about boot to kvm

- end-user/en/source/pages/migration/automatic-migration.rst
- end-user/en/source/pages/migration/data-synchronization.rst
- end-user/en/source/pages/migration/scanning.rst
> add note about error when downloading scan binary

- end-user/en/source/pages/generating/image-generate.rst
> add a note for KVM launch script

- admin/en/source/pages/config/further-config-overview.rst
- admin/en/source/pages/config/set-utc.rst
- changelog.rst
-new section
-note in changelog
> add section for setting timezone to utc

- admin/en/source/pages/install/repository-local-storage.rst
- admin/en/source/pages/install/repository-setup.rst
- admin/en/source/pages/install/repository-shared-storage.rst
> specify when to use local vs shared storage

- admin/en/source/pages/manage-resources/populate-db-example.rst
> correct path in Ubuntu populate db example

- admin/en/source/pages/upgrade/upgrade.rst
> fix file path in upgrade warning - fp10

- admin/en/source/pages/upgrade/upgrade.rst
> fix file path in upgrade warning - master

- admin/en/source/pages/config/config-amp.rst
> correct UForge Brooklyn plugin URL

- admin/en/source/pages/config/add-compute-node.rst
- admin/en/source/pages/manage-resources/manage-formats.rst
fix typo and format of step procedure
> fix typo and format

- admin/en/source/pages/monitoring/elastic-stack.rst
In Elastic Stack section. Also fix formatting issues on this page
> add info about default logstash port

- admin/en/source/pages/manage-resources/populate-db-OS.rst
- only repositories that list files are supported
> Add note for custom OS repositories

- end-user/en/source/pages/migration/migration-prereq.rst
> add a note for Windows migration to Azure

- end-user/en/source/pages/generating/image-generate.rst
> RHEL 7 supported for lightweight docker

- end-user/en/source/pages/generating/image-generate.rst
For story 13393
Also reformatted note so that list of impacted OS is clearer/more easy to read
> add info about lightweight Debian 9

- end-user/en/source/pages/migration/migration-prereq.rst
> add note about windows updates necessary for migration

- admin/en/source/pages/config/config-amp.rst
> add info about clock setting
